name: Deploy website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site-fr
        run: quarto render
        working-directory: fr

      - name: Render site-en
        run: quarto render
        working-directory: en

      - name: Prepare website
        run: |
          mkdir _site
          cp index.html _site/
	  cp style.css _site/
          cp -r en/_site-en _site/site-en
          cp -r fr/_site-fr _site/site-fr

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4